### ISSUE TITLE
Add jobs for Docker image builds

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icinga_build#13]
With a generic template so we can build the multiple Docker images we need.

**Comment by lazyfrosch** [comment]
@Crunsher put this on 1.0.0?

**Comment by Crunsher** [comment]
The jobs exist already, what's left is to adjust the existing scripts to work with our hiera supplied varaiables.

**Comment by lazyfrosch** [comment]
Has been partially updated by me. Should be fine in current master
