### ISSUE TITLE
Do test builds with a repository

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icinga_build#16]
To better test dependencies of the packages we build, we should test with repositories:

* binary job should run `createrepo` / `apt-ftparchive` for the buildresult
* test job should use the repository and install packages with apt / yum

Please don't install packages via wildcard.

Packages should be installed in a order as it makes sense.

Example for icinga2: (via the product's test script)

    apt-get install -y mysql-server
    apt-get install -y icinga2
    apt-get install -y icinga2-ido-mysql
    ...

**Comment by Crunsher** [comment]
This is implemented for snapshots and will be trivial to add for release builds once we have them
