### ISSUE TITLE
Prototype with control_repo

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/puppet-icinga_build#3]
We need to refactor the jobs so we can use a control repo to define and manage package control files: `*.spec` or `debian/*`

https://github.com/Icinga/icinga-packaging

* Use the current packaging scripts

- [ ] Conceptionize the Puppet configuration
- [ ] Remove the product-specific code and merge / add it to the control files
- [ ] Generate jobs from a configured pipeline matrix

**Comment by Crunsher** [comment]
Any update on this?
